apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-credit-analyses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter-credit-analyses
  template:
    metadata:
      labels:
        app: adapter-credit-analyses
    spec:
      containers:
        - name: adapter-credit-analyses
          image: gcr.io/possible-post-449514-a8/adapter-credit-analyses:latest
          ports:
            - containerPort: 3001
          env:
            - name: RABBITMQ_URL
              value: "amqp://user:password@credit-system-rabbitmq:5672"

---
apiVersion: v1
kind: Service
metadata:
  name: adapter-credit-analyses
spec:
  selector:
    app: adapter-credit-analyses
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
