apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-system-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-system-rabbitmq
  template:
    metadata:
      labels:
        app: credit-system-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:3-management"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: credit-system-rabbitmq
spec:
  selector:
    app: credit-system-rabbitmq
  ports:
    - name: amqp-port # Adiciona um nome para a porta
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management-port # Adiciona um nome para a porta
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-credit-analyses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter-credit-analyses
  template:
    metadata:
      labels:
        app: adapter-credit-analyses
    spec:
      containers:
        - name: adapter-credit-analyses
          image: gcr.io/possible-post-449514-a8/adapter-credit-analyses:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: RABBITMQ_URL
              value: "amqp://user:password@credit-system-rabbitmq:5672"

---
apiVersion: v1
kind: Service
metadata:
  name: adapter-credit-analyses
spec:
  selector:
    app: adapter-credit-analyses
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-credit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-credit
  template:
    metadata:
      labels:
        app: backend-credit
    spec:
      containers:
        - name: backend-credit
          image: gcr.io/possible-post-449514-a8/backend-credit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://trampay:joaovitor@35.223.168.92:5432/creditdb"
            - name: RABBITMQ_URL
              value: "amqp://user:password@credit-system-rabbitmq:5672"
          command: ["sh", "-c", "npx prisma migrate deploy && node dist/main.js"]

---
apiVersion: v1
kind: Service
metadata:
  name: backend-credit
spec:
  selector:
    app: backend-credit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
